{inputs, ...}: {
  # Both imagebuilder flakes (astro/nix-openwrt-imagebuilder and its
  # codgician/nix-immortalwrt-imagebuilder fork) only support x86_64-linux as
  # the *builder's* host system — the produced images are still for the x86/64
  # target regardless of what system builds them.
  perSystem = {
    pkgs,
    lib,
    system,
    ...
  }:
    lib.attrsets.optionalAttrs (system == "x86_64-linux") (let
      inherit (lib.lists) range;
      inherit (lib.strings) concatMapStrings;

      # Two upstream PPPoE lines: kmod-macvlan MAC-VLAN devices on top of a
      # shared WAN base device, one pppoe interface per line, load-balanced
      # via mwan3. See hosts/README.md for the multi-PPPoE background.
      pppoeLines = 2;
      lineNums = range 1 pppoeLines;

      # Guest-internal device naming for virtio-net under OpenWrt/ImmortalWrt
      # is predictably PCI-enumeration order ("eth0" then "eth1") — adjust if
      # `ip link` inside the booted VM disagrees. router-vm.nix attaches the
      # WAN macvtap first, LAN macvtap second, so:
      #   eth0 = WAN uplink (macvtap passthrough of T1's WAN-facing physical
      #          NIC) — the shared base device the macvlan lines attach to.
      #   eth1 = LAN downlink (macvtap passthrough of T1's LAN-facing NIC).
      #
      # The stock x86/64 "generic" image's default /etc/config/network binds
      # its single `lan` interface directly to `eth0` (no bridge, since a
      # generic x86 image doesn't assume a switch). Left alone, that would
      # fight the macvlan lines below for eth0, so 95-multi-pppoe first moves
      # `lan` onto eth1 before touching eth0 at all.
      wanBaseDevice = "eth0";
      lanDevice = "eth1";

      # Locally-administered, unicast MAC addresses (IEEE 802: the "02"
      # first-octet prefix sets the U/L and I/G bits appropriately) for each
      # macvlan device — must be distinct from each other and from the base
      # device so the ISP's PPPoE/DHCP session tracking treats each line as a
      # separate client.
      macFor = n: "02:00:00:00:00:${lib.strings.fixedWidthString 2 "0" (toString n)}";

      mkMultiPppoeFiles = pkgs.runCommand "openwrt-t640-multi-pppoe-files" {} ''
        mkdir -p "$out/etc/uci-defaults"
        cat > "$out/etc/uci-defaults/95-multi-pppoe" <<'UCIDEFAULTS'
        #!/bin/sh
        # Multi-PPPoE WAN: one kmod-macvlan device + one pppoe interface per
        # ISP line on top of a shared physical/virtio WAN device, balanced via
        # mwan3. Generated by flake/openwrt-images.nix — edit the Nix source
        # and rebuild the image rather than hand-editing a booted router.

        # Free the WAN base device from the image's default `lan` binding
        # first (see the wanBaseDevice/lanDevice comment in openwrt-images.nix)
        # — otherwise the macvlan devices below would be layered on top of an
        # interface still serving as the LAN bridge member.
        uci -q batch <<EOI
        set network.lan.device='${lanDevice}'
        EOI

        ${concatMapStrings (n: ''
            uci -q batch <<EOI
            set network.wanmv${toString n}=device
            set network.wanmv${toString n}.type='macvlan'
            set network.wanmv${toString n}.ifname='${wanBaseDevice}'
            set network.wanmv${toString n}.name='wanmv${toString n}'
            set network.wanmv${toString n}.macaddr='${macFor n}'

            set network.wan${toString n}=interface
            set network.wan${toString n}.proto='pppoe'
            set network.wan${toString n}.device='wanmv${toString n}'
            set network.wan${toString n}.ipv6='auto'
            EOI
          '')
          lineNums}
        # PLACEHOLDER credentials — never committed for real. Enter the actual
        # PPPoE username/password for each line once, after first boot, via
        # LuCI (Network > Interfaces > wanN > Edit) or:
        #   uci set network.wanN.username='...'
        #   uci set network.wanN.password='...'
        #   uci commit network && /etc/init.d/network reload
        # (N = 1..${toString pppoeLines}). See hosts/README.md.
        ${concatMapStrings (n: ''
            uci -q batch <<EOI
            set network.wan${toString n}.username='CHANGEME-line${toString n}-username'
            set network.wan${toString n}.password='CHANGEME-line${toString n}-password'
            EOI
          '')
          lineNums}

        # wan firewall zone: cover every pppoe interface (assumes the default
        # image ships firewall zones in the usual lan=0, wan=1 order).
        uci -q batch <<EOI
        del_list firewall.@zone[1].network='wan'
        ${concatMapStrings (n: "add_list firewall.@zone[1].network='wan${toString n}'\n") lineNums}
        EOI

        # mwan3: one interface + member per line, balanced (equal-weight)
        # policy by default. To switch to primary/backup failover instead,
        # give the backup line a higher metric (e.g. '2') than the primary
        # (metric '1') — see hosts/README.md.
        uci -q batch <<EOI
        ${concatMapStrings (n: ''
            set mwan3.wan${toString n}=interface
            set mwan3.wan${toString n}.enabled='1'
            set mwan3.wan${toString n}.family='ipv4'
            set mwan3.wan${toString n}.reliability='1'
            set mwan3.wan${toString n}.count='1'
            set mwan3.wan${toString n}.timeout='2'
            set mwan3.wan${toString n}.interval='5'
            set mwan3.wan${toString n}.down='3'
            set mwan3.wan${toString n}.up='3'

            set mwan3.wan${toString n}_m1_w3=member
            set mwan3.wan${toString n}_m1_w3.interface='wan${toString n}'
            set mwan3.wan${toString n}_m1_w3.metric='1'
            set mwan3.wan${toString n}_m1_w3.weight='3'
          '')
          lineNums}

        set mwan3.balanced=policy
        ${concatMapStrings (n: "add_list mwan3.balanced.use_member='wan${toString n}_m1_w3'\n") lineNums}

        set mwan3.default_rule=rule
        set mwan3.default_rule.dest_ip='0.0.0.0/0'
        set mwan3.default_rule.use_policy='balanced'
        EOI

        uci commit network
        uci commit firewall
        uci commit mwan3

        exit 0
        UCIDEFAULTS
        chmod +x "$out/etc/uci-defaults/95-multi-pppoe"
      '';

      commonArgs = {
        inherit pkgs;
        target = "x86";
        variant = "64";
        profile = "generic";
        packages = [
          "kmod-macvlan"
          "kmod-8021q" # not wired up by 95-multi-pppoe above, kept available for future VLAN-tagged WAN lines
          "mwan3"
          "luci-app-mwan3"
          "kmod-pppoe"
          "ppp-mod-pppoe"
        ];
        files = mkMultiPppoeFiles;
      };
    in {
      packages = {
        openwrt-t640-router = inputs.openwrt-imagebuilder.lib.build commonArgs;
        immortalwrt-t640-router = inputs.immortalwrt-imagebuilder.lib.build commonArgs;
      };
    });
}
