# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  Iris = {
    pname = "Iris";
    version = "v0.3.1";
    src = fetchurl {
      url = "https://github.com/ahmetb/Iris/releases/download/v0.3.1/Iris-v0.3.1.zip";
      sha256 = "sha256-QEEN9mEXXO0ONitiT6SH86nd28iRbZ3yctTKDZIlKNg=";
    };
  };
  LiveWallpaperMacOS = {
    pname = "LiveWallpaperMacOS";
    version = "V2.3";
    src = fetchurl {
      url = "https://github.com/thusvill/LiveWallpaperMacOS/releases/download/V2.3/LiveWallpaper.dmg";
      sha256 = "sha256-GW6tSVCrRo8Dx/s6gyRjsWC0dxFIw8J28GBSqrnfaIo=";
    };
  };
  LosslessSwitcher = {
    pname = "LosslessSwitcher";
    version = "2.0";
    src = fetchurl {
      url = "https://github.com/vincentneo/LosslessSwitcher/releases/download/2.0/LosslessSwitcher2.app.zip";
      sha256 = "sha256-vyzWG5r6GgyqekkbJcyyzBLwnbO5gxwNgUhUCD3Oroo=";
    };
  };
  MacKernelSDK = {
    pname = "MacKernelSDK";
    version = "3f750085caa17ec3a7880f11c11bf4f48cd6a164";
    src = fetchFromGitHub {
      owner = "acidanthera";
      repo = "MacKernelSDK";
      rev = "3f750085caa17ec3a7880f11c11bf4f48cd6a164";
      fetchSubmodules = false;
      sha256 = "sha256-utr2hNf0/Vrd7QFHBJvfMlOr0WaDv/2B5xT9tu7+9VE=";
    };
    date = "2026-09-23";
  };
  MultiSoundChanger = {
    pname = "MultiSoundChanger";
    version = "1.0.1-BetterDisplay";
    src = fetchurl {
      url = "https://github.com/aonez/MultiSoundChanger/releases/download/1.0.1-BetterDisplay/MultiSoundChanger+BetterDisplay.zip";
      sha256 = "sha256-iY6V48247mNEgQ73QTZ5RJBsiNEji0bTVt8q43BIfJo=";
    };
  };
  Spaceman = {
    pname = "Spaceman";
    version = "1.27.0";
    src = fetchurl {
      url = "https://github.com/ruittenb/Spaceman/releases/download/v1.27.0/Spaceman-1.27.0.dmg";
      sha256 = "sha256-1TLBWzkjtwcLfwk26Zjm90A1TgZkuVv5codf/YL+fnE=";
    };
  };
  VoltageShift = {
    pname = "VoltageShift";
    version = "4fef84ffe10b7e79c4d6efa043e7873820590bd0";
    src = fetchFromGitHub {
      owner = "asepms92";
      repo = "VoltageShift";
      rev = "4fef84ffe10b7e79c4d6efa043e7873820590bd0";
      fetchSubmodules = false;
      sha256 = "sha256-GKWBEuuq/vPquGx4vYUI2uEf3uXEo+6uJrDVYnfYg3Q=";
    };
    date = "2025-09-19";
  };
  agevault = {
    pname = "agevault";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "ndavd";
      repo = "agevault";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-Uc4g1dBGIIXciTbZRi7ADfQGiGNe0447kZ+unY1L+w8=";
    };
  };
  clamav-unofficial-sigs = {
    pname = "clamav-unofficial-sigs";
    version = "948a1fb84c15a71910456561cec384a978b13412";
    src = fetchFromGitHub {
      owner = "extremeshok";
      repo = "clamav-unofficial-sigs";
      rev = "948a1fb84c15a71910456561cec384a978b13412";
      fetchSubmodules = false;
      sha256 = "sha256-RpAHJ+l5Ro+2p6CvmLjwlvYouBnJhdg34oYZOYhR6Bk=";
    };
    date = "2026-07-02";
  };
  dmgwiz = {
    pname = "dmgwiz";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "citruz";
      repo = "dmgwiz";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-shNpuVs67UF+2TY7u08sF2J7TkWzwy/DVyCAaxdB78o=";
    };
  };
  get-apple-firmware = {
    pname = "get-apple-firmware";
    version = "986f5a79d43b75d93d84b8d57bc338853b51a0e0";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/t2linux/wiki/986f5a79d43b75d93d84b8d57bc338853b51a0e0/docs/tools/firmware.sh";
      sha256 = "sha256-wcHYqiW7XwieRszQ2XOPwTv714T0maqSRGbGkPBZlh4=";
    };
    date = "2026-09-24";
  };
  hyperhdr-aarch64 = {
    pname = "hyperhdr-aarch64";
    version = "22.0.0";
    src = fetchurl {
      url = "https://github.com/awawa-dev/HyperHDR/releases/download/v22.0.0.0/HyperHDR-22.0.0-macOS-arm64.dmg";
      sha256 = "sha256-yC6e8HeX3rs5vKp/mGXCLFSjvk/eQbcoTSNMzeQbPPc=";
    };
  };
  hyperhdr-x86_64 = {
    pname = "hyperhdr-x86_64";
    version = "22.0.0";
    src = fetchurl {
      url = "https://github.com/awawa-dev/HyperHDR/releases/download/v22.0.0.0/HyperHDR-22.0.0-macOS-x86_64.dmg";
      sha256 = "sha256-plCH3tvZiibd5/IxkGE42WqaG3VmRsmUcjHUEbHkIlQ=";
    };
  };
  launchdeck-aarch64 = {
    pname = "launchdeck-aarch64";
    version = "0.1.4";
    src = fetchurl {
      url = "https://github.com/sderosiaux/launchdeck/releases/download/v0.1.4/launchdeck-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-aVYz/vOOfcWq/nMhHl1QRZkGwmyINJGWHPTT8nkdRBc=";
    };
  };
  launchdeck-x86_64 = {
    pname = "launchdeck-x86_64";
    version = "0.1.4";
    src = fetchurl {
      url = "https://github.com/sderosiaux/launchdeck/releases/download/v0.1.4/launchdeck-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-si6awEv8PEV4eBK0eZMaPxXL0iUoLVubq/O2OLA8ls8=";
    };
  };
  libxls = {
    pname = "libxls";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/libxls/libxls/releases/download/v1.6.3/libxls-1.6.3.tar.gz";
      sha256 = "sha256-svuDbqC1JTo1L7XKVXQuKfBvlPlCHFuO7M7y5dQ/Yiw=";
    };
  };
  menubar-dock = {
    pname = "menubar-dock";
    version = "v4.8.0";
    src = fetchurl {
      url = "https://github.com/EthanSK/Menu-Bar-Dock/releases/download/v4.8.0/Menu-Bar-Dock-v4.8.0.zip";
      sha256 = "sha256-6qjcdk2+dx5RMhHvzQS2S1yDOclwSmeZJT7lCffJSBI=";
    };
  };
  mutt = {
    pname = "mutt";
    version = "ebe3819fc05bb016499110eb403754138e2d814b";
    src = fetchFromGitHub {
      owner = "muttmua";
      repo = "mutt";
      rev = "ebe3819fc05bb016499110eb403754138e2d814b";
      fetchSubmodules = false;
      sha256 = "sha256-3zxVRMarD8DpNmX0rkR65hJX0GmisV9UF8/Mm21/LAU=";
    };
    date = "2026-10-09";
  };
  option-analysis = {
    pname = "option-analysis";
    version = "57f3b1eec9705f2a9f01758b4c9c50f22ea97453";
    src = fetchFromGitHub {
      owner = "harsh-vardhhan";
      repo = "option-analysis";
      rev = "57f3b1eec9705f2a9f01758b4c9c50f22ea97453";
      fetchSubmodules = false;
      sha256 = "sha256-kG5Gf67FRtsxUMWJLw10zjdgKB+aC16iZs8kIDKdKmc=";
    };
    date = "2026-06-07";
  };
  reapack-arm64 = {
    pname = "reapack-arm64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-arm64.dylib";
      sha256 = "sha256-x2cPOy5AW5A31JsZQaTYw3Yv/zJs7MDFisT67KFx8Hs=";
    };
  };
  reapack-x86_64 = {
    pname = "reapack-x86_64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-x86_64.dylib";
      sha256 = "sha256-SLJhl042ZxOEypAqOz1aYUF49Asb63wTjHQUEOpdfZ4=";
    };
  };
  reaper-sws-arm64 = {
    pname = "reaper-sws-arm64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-arm64.dylib";
      sha256 = "sha256-jmuob0qslYhxiE2ShfTwY4RJAKBLJSUb+VBEM0sQPbo=";
    };
  };
  reaper-sws-python32 = {
    pname = "reaper-sws-python32";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python32.py";
      sha256 = "sha256-np2r568csSdIS7VZHDASroZlXhpfxXwNn0gROTinWU4=";
    };
  };
  reaper-sws-python64 = {
    pname = "reaper-sws-python64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python64.py";
      sha256 = "sha256-GDlvfARg1g5oTH2itEug6Auxr9iFlPDdGueInGmHqSI=";
    };
  };
  reaper-sws-x86_64 = {
    pname = "reaper-sws-x86_64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-x86_64.dylib";
      sha256 = "sha256-c0enRIXFN+dMDdxTQ3hFv0almTF0dfrSHILNigJp2Js=";
    };
  };
  smcFanControl = {
    pname = "smcFanControl";
    version = "e1bd672bcd2d72eddff9b6da7b9cae38e35c4206";
    src = fetchFromGitHub {
      owner = "hholtmann";
      repo = "smcFanControl";
      rev = "e1bd672bcd2d72eddff9b6da7b9cae38e35c4206";
      fetchSubmodules = false;
      sha256 = "sha256-Ma1+E/i6LTvKpSRu2uASAC/EAsYM+cIWInWBzH4MkPw=";
    };
    date = "2022-12-03";
  };
  spotify-player = {
    pname = "spotify-player";
    version = "v0.25.1";
    src = fetchFromGitHub {
      owner = "aome510";
      repo = "spotify-player";
      rev = "v0.25.1";
      fetchSubmodules = false;
      sha256 = "sha256-lJOHhrJ6ser1vs2m0pUnDpbnSgTtdTX/yXhCjvzCrTM=";
    };
  };
  tccutil = {
    pname = "tccutil";
    version = "v1.5.5";
    src = fetchFromGitHub {
      owner = "jacobsalmela";
      repo = "tccutil";
      rev = "v1.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-pEVH8VZp8fsXMpIu/SlZ6JmwH/oKKGm7ANxZZlEPfUk=";
    };
  };
  uniclipboard-cli-aarch64-darwin = {
    pname = "uniclipboard-cli-aarch64-darwin";
    version = "1.1.2";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v1.1.2/uniclipboard-cli-1.1.2-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-vsFyTV+fhDP8kvNhBThvWd4dkdAInOiEa4Wj3fk1z6g=";
    };
  };
  uniclipboard-cli-aarch64-linux = {
    pname = "uniclipboard-cli-aarch64-linux";
    version = "1.1.2";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v1.1.2/uniclipboard-cli-1.1.2-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-gV7T1QCBWy705XhT0Qf+PY+9Qo3dgfWqW3AQtTOGsWQ=";
    };
  };
  uniclipboard-cli-x86_64-darwin = {
    pname = "uniclipboard-cli-x86_64-darwin";
    version = "1.1.2";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v1.1.2/uniclipboard-cli-1.1.2-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-qLtpoVkE4JjaOhY2kh7jcH7SbD2FyUBd7fPZON/eUzM=";
    };
  };
  uniclipboard-cli-x86_64-linux = {
    pname = "uniclipboard-cli-x86_64-linux";
    version = "1.1.2";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v1.1.2/uniclipboard-cli-1.1.2-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-nlI2ZvfaJ/wEsoKEQz5HrIqlYU8GBnRBa6vlf7JbQIQ=";
    };
  };
  warpd = {
    pname = "warpd";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "atuan26";
      repo = "warpd";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-ngWQdGKvHxng0C1LlmYHMWjcH4mzgrEFr6DvEa6LdUE=";
    };
  };
  yara-rules = {
    pname = "yara-rules";
    version = "0f93570194a80d2f2032869055808b0ddcdfb360";
    src = fetchFromGitHub {
      owner = "Yara-Rules";
      repo = "rules";
      rev = "0f93570194a80d2f2032869055808b0ddcdfb360";
      fetchSubmodules = false;
      sha256 = "sha256-AtyRHS3mbemHXErpRONUOWVyVDkVKw96uluzKz5t8K4=";
    };
    date = "2022-04-12";
  };
  zerobrew-zb-aarch64 = {
    pname = "zerobrew-zb-aarch64";
    version = "0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zb-darwin-arm64";
      sha256 = "sha256-M828ABO6uCtUDH32GdjcFR/nLJQiXmVyMaF6xagf3KQ=";
    };
  };
  zerobrew-zb-x86_64 = {
    pname = "zerobrew-zb-x86_64";
    version = "0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zb-darwin-x64";
      sha256 = "sha256-CDicChVQHPv5Rx4Uu/40sopURDwWnWjcQiaVQAn4wfs=";
    };
  };
  zerobrew-zbx-aarch64 = {
    pname = "zerobrew-zbx-aarch64";
    version = "0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zbx-darwin-arm64";
      sha256 = "sha256-JMRRiDqKKdQUaIQ3ak6zbXxGaThdGsSicTIVjfn9gSM=";
    };
  };
  zerobrew-zbx-x86_64 = {
    pname = "zerobrew-zbx-x86_64";
    version = "0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zbx-darwin-x64";
      sha256 = "sha256-GEGGHL9bwsNUmcEdosWfYTZCgeC2HNuFfDHk0FJRVQw=";
    };
  };
}
