# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  Iris = {
    pname = "Iris";
    version = "v0.2.1";
    src = fetchurl {
      url = "https://github.com/ahmetb/Iris/releases/download/v0.2.1/Iris-v0.2.1.zip";
      sha256 = "sha256-JZoKDwPCc0PXQpCyY8oe77XZymQ7NTMgWf0Kr+IE26o=";
    };
  };
  LiveWallpaperMacOS = {
    pname = "LiveWallpaperMacOS";
    version = "V2.3";
    src = fetchurl {
      url = "https://github.com/thusvill/LiveWallpaperMacOS/releases/download/V2.3/LiveWallpaper.dmg";
      sha256 = "sha256-GW6tSVCrRo8Dx/s6gyRjsWC0dxFIw8J28GBSqrnfaIo=";
    };
  };
  LosslessSwitcher = {
    pname = "LosslessSwitcher";
    version = "2.0";
    src = fetchurl {
      url = "https://github.com/vincentneo/LosslessSwitcher/releases/download/2.0/LosslessSwitcher2.app.zip";
      sha256 = "sha256-vyzWG5r6GgyqekkbJcyyzBLwnbO5gxwNgUhUCD3Oroo=";
    };
  };
  MacKernelSDK = {
    pname = "MacKernelSDK";
    version = "05094e5e88cec7caedbfb35e8449ed0db94bf95b";
    src = fetchFromGitHub {
      owner = "acidanthera";
      repo = "MacKernelSDK";
      rev = "05094e5e88cec7caedbfb35e8449ed0db94bf95b";
      fetchSubmodules = false;
      sha256 = "sha256-5ZtiNjYrriqgNGCeHseASzxpDxQ6wXNoagx0/uOS+yE=";
    };
    date = "2026-06-19";
  };
  MultiSoundChanger = {
    pname = "MultiSoundChanger";
    version = "1.0.1-BetterDisplay";
    src = fetchurl {
      url = "https://github.com/aonez/MultiSoundChanger/releases/download/1.0.1-BetterDisplay/MultiSoundChanger+BetterDisplay.zip";
      sha256 = "sha256-iY6V48247mNEgQ73QTZ5RJBsiNEji0bTVt8q43BIfJo=";
    };
  };
  Spaceman = {
    pname = "Spaceman";
    version = "1.23.6";
    src = fetchurl {
      url = "https://github.com/ruittenb/Spaceman/releases/download/v1.23.6/Spaceman-1.23.6.dmg";
      sha256 = "sha256-pdeGo99gW9oUTgvP2sv03JzmhjsgitmgoNre8bYQQTE=";
    };
  };
  VoltageShift = {
    pname = "VoltageShift";
    version = "4fef84ffe10b7e79c4d6efa043e7873820590bd0";
    src = fetchFromGitHub {
      owner = "asepms92";
      repo = "VoltageShift";
      rev = "4fef84ffe10b7e79c4d6efa043e7873820590bd0";
      fetchSubmodules = false;
      sha256 = "sha256-GKWBEuuq/vPquGx4vYUI2uEf3uXEo+6uJrDVYnfYg3Q=";
    };
    date = "2025-09-19";
  };
  agevault = {
    pname = "agevault";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "ndavd";
      repo = "agevault";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-Uc4g1dBGIIXciTbZRi7ADfQGiGNe0447kZ+unY1L+w8=";
    };
  };
  clamav-unofficial-sigs = {
    pname = "clamav-unofficial-sigs";
    version = "948a1fb84c15a71910456561cec384a978b13412";
    src = fetchFromGitHub {
      owner = "extremeshok";
      repo = "clamav-unofficial-sigs";
      rev = "948a1fb84c15a71910456561cec384a978b13412";
      fetchSubmodules = false;
      sha256 = "sha256-RpAHJ+l5Ro+2p6CvmLjwlvYouBnJhdg34oYZOYhR6Bk=";
    };
    date = "2026-07-02";
  };
  dmgwiz = {
    pname = "dmgwiz";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "citruz";
      repo = "dmgwiz";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-8iuucOOLKd9WoFEFwn5xP1ZZ2C1GAQeyVO6mSdDYb8Y=";
    };
  };
  get-apple-firmware = {
    pname = "get-apple-firmware";
    version = "63823db38b4287e9a9ab2bed87b6095665fee63a";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/t2linux/wiki/63823db38b4287e9a9ab2bed87b6095665fee63a/docs/tools/firmware.sh";
      sha256 = "sha256-wcHYqiW7XwieRszQ2XOPwTv714T0maqSRGbGkPBZlh4=";
    };
    date = "2026-07-29";
  };
  iSMC = {
    pname = "iSMC";
    version = "0.17.2";
    src = fetchurl {
      url = "https://github.com/dkorunic/iSMC/releases/download/v0.17.2/iSMC_Darwin_all.tar.gz";
      sha256 = "sha256-BpM7vB2UKL5fSeo5OidWScWJxnAoIie7VDWNL0f2JUE=";
    };
  };
  launchdeck-aarch64 = {
    pname = "launchdeck-aarch64";
    version = "0.1.3";
    src = fetchurl {
      url = "https://github.com/sderosiaux/launchdeck/releases/download/v0.1.3/launchdeck-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-/h0/+DAxnki09aw4lm/+4nAsxgletSor2E+G4CU3POA=";
    };
  };
  launchdeck-x86_64 = {
    pname = "launchdeck-x86_64";
    version = "0.1.3";
    src = fetchurl {
      url = "https://github.com/sderosiaux/launchdeck/releases/download/v0.1.3/launchdeck-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-BfhQue0/kRa6Exuyz5lfQa1dSAd9/X5AXW7AneN1yhc=";
    };
  };
  libxls = {
    pname = "libxls";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/libxls/libxls/releases/download/v1.6.3/libxls-1.6.3.tar.gz";
      sha256 = "sha256-svuDbqC1JTo1L7XKVXQuKfBvlPlCHFuO7M7y5dQ/Yiw=";
    };
  };
  menubar-dock = {
    pname = "menubar-dock";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "joaquinpiedracueva";
      repo = "menubar-dock";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-EA0FllpEhcp2VxVLMVqLCpmlvt0F+xnuKzMsaMXzfDw=";
    };
  };
  mutt = {
    pname = "mutt";
    version = "dda22dba0990645ed7961899a87ae5b1ea36d2e7";
    src = fetchFromGitHub {
      owner = "muttmua";
      repo = "mutt";
      rev = "dda22dba0990645ed7961899a87ae5b1ea36d2e7";
      fetchSubmodules = false;
      sha256 = "sha256-sVRXaENy/KkmsmhUJLs/6jJlr0qMkGyOxBezHChUna8=";
    };
    date = "2026-07-31";
  };
  nchat-aarch64-darwin = {
    pname = "nchat-aarch64-darwin";
    version = "5.17.26";
    src = fetchurl {
      url = "https://github.com/d99kris/nchat/releases/download/v5.17.26/nchat-5.17.26-macos-arm64.tar.gz";
      sha256 = "sha256-xNYpQOok2Ts5E5ITbjzbDBLmOA+eN/hnk/QUYObSvAU=";
    };
  };
  nchat-aarch64-linux = {
    pname = "nchat-aarch64-linux";
    version = "5.17.26";
    src = fetchurl {
      url = "https://github.com/d99kris/nchat/releases/download/v5.17.26/nchat-5.17.26-linux-arm64-glibc.tar.gz";
      sha256 = "sha256-ooIsPj6PM8fHG8HrgDtRhK4CV8YychpS/o9w0GgjDqU=";
    };
  };
  nchat-x86_64-linux = {
    pname = "nchat-x86_64-linux";
    version = "5.17.26";
    src = fetchurl {
      url = "https://github.com/d99kris/nchat/releases/download/v5.17.26/nchat-5.17.26-linux-x86_64-glibc.tar.gz";
      sha256 = "sha256-9wyc1euQhQ/1/kazpzkXkLR5Jwak3xTasmlEZljuUAU=";
    };
  };
  option-analysis = {
    pname = "option-analysis";
    version = "57f3b1eec9705f2a9f01758b4c9c50f22ea97453";
    src = fetchFromGitHub {
      owner = "harsh-vardhhan";
      repo = "option-analysis";
      rev = "57f3b1eec9705f2a9f01758b4c9c50f22ea97453";
      fetchSubmodules = false;
      sha256 = "sha256-kG5Gf67FRtsxUMWJLw10zjdgKB+aC16iZs8kIDKdKmc=";
    };
    date = "2026-06-07";
  };
  reapack-arm64 = {
    pname = "reapack-arm64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-arm64.dylib";
      sha256 = "sha256-x2cPOy5AW5A31JsZQaTYw3Yv/zJs7MDFisT67KFx8Hs=";
    };
  };
  reapack-x86_64 = {
    pname = "reapack-x86_64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-x86_64.dylib";
      sha256 = "sha256-SLJhl042ZxOEypAqOz1aYUF49Asb63wTjHQUEOpdfZ4=";
    };
  };
  reaper-sws-arm64 = {
    pname = "reaper-sws-arm64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-arm64.dylib";
      sha256 = "sha256-jmuob0qslYhxiE2ShfTwY4RJAKBLJSUb+VBEM0sQPbo=";
    };
  };
  reaper-sws-python32 = {
    pname = "reaper-sws-python32";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python32.py";
      sha256 = "sha256-np2r568csSdIS7VZHDASroZlXhpfxXwNn0gROTinWU4=";
    };
  };
  reaper-sws-python64 = {
    pname = "reaper-sws-python64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python64.py";
      sha256 = "sha256-GDlvfARg1g5oTH2itEug6Auxr9iFlPDdGueInGmHqSI=";
    };
  };
  reaper-sws-x86_64 = {
    pname = "reaper-sws-x86_64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-x86_64.dylib";
      sha256 = "sha256-c0enRIXFN+dMDdxTQ3hFv0almTF0dfrSHILNigJp2Js=";
    };
  };
  simplex-chat-cli-aarch64-darwin = {
    pname = "simplex-chat-cli-aarch64-darwin";
    version = "7.0.0";
    src = fetchurl {
      url = "https://github.com/simplex-chat/simplex-chat/releases/download/v7.0.0/simplex-chat-macos-aarch64";
      sha256 = "sha256-soN7jR54IoW9rvypi2HwPLA4SUirQydbG+17KWRZNZA=";
    };
  };
  simplex-chat-cli-aarch64-linux = {
    pname = "simplex-chat-cli-aarch64-linux";
    version = "7.0.0";
    src = fetchurl {
      url = "https://github.com/simplex-chat/simplex-chat/releases/download/v7.0.0/simplex-chat-ubuntu-24_04-aarch64";
      sha256 = "sha256-cKQ5aZBTwdm3+D/vnc3V45GltmSKKKeXtOG3MKCLHBs=";
    };
  };
  simplex-chat-cli-x86_64-darwin = {
    pname = "simplex-chat-cli-x86_64-darwin";
    version = "7.0.0";
    src = fetchurl {
      url = "https://github.com/simplex-chat/simplex-chat/releases/download/v7.0.0/simplex-chat-macos-x86-64";
      sha256 = "sha256-JSxWasGrrRg85sjoJM24Mg7n3UIMnl+XM4XS8g5tW1Y=";
    };
  };
  simplex-chat-cli-x86_64-linux = {
    pname = "simplex-chat-cli-x86_64-linux";
    version = "7.0.0";
    src = fetchurl {
      url = "https://github.com/simplex-chat/simplex-chat/releases/download/v7.0.0/simplex-chat-ubuntu-24_04-x86_64";
      sha256 = "sha256-hScqVYzWkFnw36mWNLLFztsX83RGDJzsRNl3evEAUME=";
    };
  };
  smcFanControl = {
    pname = "smcFanControl";
    version = "e1bd672bcd2d72eddff9b6da7b9cae38e35c4206";
    src = fetchFromGitHub {
      owner = "hholtmann";
      repo = "smcFanControl";
      rev = "e1bd672bcd2d72eddff9b6da7b9cae38e35c4206";
      fetchSubmodules = false;
      sha256 = "sha256-Ma1+E/i6LTvKpSRu2uASAC/EAsYM+cIWInWBzH4MkPw=";
    };
    date = "2022-12-03";
  };
  spotify-player = {
    pname = "spotify-player";
    version = "v0.24.1";
    src = fetchFromGitHub {
      owner = "aome510";
      repo = "spotify-player";
      rev = "v0.24.1";
      fetchSubmodules = false;
      sha256 = "sha256-+GADmRl4XMwV8TfYZjEeyKDDfda3bDPzeerhYryX6vA=";
    };
  };
  tccutil = {
    pname = "tccutil";
    version = "v1.5.1";
    src = fetchFromGitHub {
      owner = "jacobsalmela";
      repo = "tccutil";
      rev = "v1.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-gb67xM8daBA03Oq8XCkLdNcPjx5qymz0U859gRaHofs=";
    };
  };
  uniclipboard-cli-aarch64-darwin = {
    pname = "uniclipboard-cli-aarch64-darwin";
    version = "0.19.1";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v0.19.1/uniclipboard-cli-0.19.1-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-34lmqgtGLGneijBKmfcSKOoskRn6OjJ6M7tI35sntOY=";
    };
  };
  uniclipboard-cli-aarch64-linux = {
    pname = "uniclipboard-cli-aarch64-linux";
    version = "0.19.1";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v0.19.1/uniclipboard-cli-0.19.1-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-Z9K5ohfPHGhgHHGdYqo2RILi/EOKwHrFFVGtiiF0k/Q=";
    };
  };
  uniclipboard-cli-x86_64-darwin = {
    pname = "uniclipboard-cli-x86_64-darwin";
    version = "0.19.1";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v0.19.1/uniclipboard-cli-0.19.1-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-aeJFl1orSFgIvl2rqxakcEWc85Dh7ODkwPiqUSQtwt8=";
    };
  };
  uniclipboard-cli-x86_64-linux = {
    pname = "uniclipboard-cli-x86_64-linux";
    version = "0.19.1";
    src = fetchurl {
      url = "https://github.com/UniClipboard/UniClipboard/releases/download/v0.19.1/uniclipboard-cli-0.19.1-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-zXBnmc7Ivscs/hxIi/13C2KTQ6iCRXxtIHnimls18fM=";
    };
  };
  wacli-aarch64-darwin = {
    pname = "wacli-aarch64-darwin";
    version = "0.15.2";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.15.2/wacli_0.15.2_darwin_arm64.tar.gz";
      sha256 = "sha256-9NFiyKMfts3Z6tWV5U6AqlPUFwi5xXUhcX7Lt6xuMPc=";
    };
  };
  wacli-aarch64-linux = {
    pname = "wacli-aarch64-linux";
    version = "0.15.2";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.15.2/wacli_0.15.2_linux_arm64.tar.gz";
      sha256 = "sha256-W4h4WqLF2ahta2Z51IIqTEkBEAOtivOVgIl5fXoLggc=";
    };
  };
  wacli-x86_64-darwin = {
    pname = "wacli-x86_64-darwin";
    version = "0.15.2";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.15.2/wacli_0.15.2_darwin_amd64.tar.gz";
      sha256 = "sha256-ciAH20RPzn9MFsp5L8IlPlnueRU4P1ArRUw9l3Gm0ps=";
    };
  };
  wacli-x86_64-linux = {
    pname = "wacli-x86_64-linux";
    version = "0.15.2";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.15.2/wacli_0.15.2_linux_amd64.tar.gz";
      sha256 = "sha256-a6iOzss0qLxilVvArC1BSAvVXMKX/GG2hRNeH7IWuvY=";
    };
  };
  warpd = {
    pname = "warpd";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "atuan26";
      repo = "warpd";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-ngWQdGKvHxng0C1LlmYHMWjcH4mzgrEFr6DvEa6LdUE=";
    };
  };
  yara-rules = {
    pname = "yara-rules";
    version = "0f93570194a80d2f2032869055808b0ddcdfb360";
    src = fetchFromGitHub {
      owner = "Yara-Rules";
      repo = "rules";
      rev = "0f93570194a80d2f2032869055808b0ddcdfb360";
      fetchSubmodules = false;
      sha256 = "sha256-AtyRHS3mbemHXErpRONUOWVyVDkVKw96uluzKz5t8K4=";
    };
    date = "2022-04-12";
  };
  zerobrew-zb-aarch64 = {
    pname = "zerobrew-zb-aarch64";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.3.2/zb-darwin-arm64";
      sha256 = "sha256-YfflR1vFAmnBiqRaWZ6L/u3+9ZdAdFzH2stQ9xth11s=";
    };
  };
  zerobrew-zb-x86_64 = {
    pname = "zerobrew-zb-x86_64";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.3.2/zb-darwin-x64";
      sha256 = "sha256-stpkqgW9eBdwWDnun1iZsOqxVUFnRVzLhQ6FEKpDtBM=";
    };
  };
  zerobrew-zbx-aarch64 = {
    pname = "zerobrew-zbx-aarch64";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.3.2/zbx-darwin-arm64";
      sha256 = "sha256-NbiJDkH3pyfl4Jg0ABEi0l2LDHdyewoMvW1QZBR81iw=";
    };
  };
  zerobrew-zbx-x86_64 = {
    pname = "zerobrew-zbx-x86_64";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.3.2/zbx-darwin-x64";
      sha256 = "sha256-foIIGS5062IfSdrtJRu/VMmuib2mv9m9MlIURVtzyNA=";
    };
  };
}
