name: Publish tags to FlakeHub
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    environment:
      name: dev
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@main"
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - name: Set env var
        run: echo "INFRA_NIXCFG=$(pwd)" >> "$GITHUB_ENV"
      - uses: "DeterminateSystems/nix-installer-action@main"
        with:
          determinate: true
      - name: SSH-agent with auth for private repos
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          name: "DivitMittal/infra-nixCfg"
          tag: "${{ inputs.tag }}"
          include-output-paths: true
